# docker-compose.yml
version: "3.8"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb1
    ports:
      - "27017:27017"
    #networks:
      #- app-network
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/apache:/var/log/apache2
      - ./src/helloworld:/usr/local/apache2/htdocs/backend
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src/backend:/usr/local/apache2/htdocs/backend
    working_dir: /usr/local/apache2/htdocs/backend
  composer:
    container_name: composer
    image: composer/composer
    volumes:
      - ./src/backend:/usr/local/apache2/htdocs/backend
    working_dir: /usr/local/apache2/htdocs/backend
    command: install
  vuejs:
    container_name: vuejs
    build:
      context: ./src/vuejs
    ports:
      - "5173:5173"
    volumes:
      - ./src/vuejs:/src
    working_dir: /src
    command: npm run dev -- --host
